/**
 * Dataset initial de secours (Fallback Jobs)
 * Assure un affichage instantané et résilient même hors-ligne ou avant le premier déclenchement Cron.
 */
export const FALLBACK_JOBS = [
  {
    id: "fallback-fr-1",
    title: "Senior Fullstack Engineer (TypeScript / Node.js / React)",
    company: "GitBook",
    company_logo: "https://remotive.com/job/1919266/logo",
    url: "https://www.gitbook.com/careers",
    category: "Tech & Dev",
    categoryId: "tech",
    categoryIcon: "💻",
    tags: ["TypeScript", "Node.js", "React", "Cloudflare", "TailwindCSS"],
    job_type: "Full-time (CDI)",
    location: "France / Europe (100% Remote)",
    region: "France & Francophonie",
    regionId: "france",
    regionFlag: "🇫🇷",
    salary: "65 000 € - 85 000 € / an",
    published_at: "2026-08-17T09:00:00.000Z",
    description_snippet:
      "Rejoignez notre équipe technique distribuée pour concevoir la nouvelle génération d'outils de documentation collaborative. Télétravail complet en France ou Europe, budget équipement et mutuelle premium.",
    source: "Remotive",
    language: "fr",
  },
  {
    id: "fallback-fr-2",
    title: "Lead DevOps / Platform Architect (AWS, Terraform, Kubernetes)",
    company: "PayFit",
    company_logo: "",
    url: "https://payfit.com/careers",
    category: "DevOps & Cloud",
    categoryId: "devops",
    categoryIcon: "☁️",
    tags: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Docker"],
    job_type: "Full-time (CDI)",
    location: "France / Francophonie (100% Télétravail)",
    region: "France & Francophonie",
    regionId: "france",
    regionFlag: "🇫🇷",
    salary: "75 000 € - 95 000 € / an",
    published_at: "2026-08-17T08:30:00.000Z",
    description_snippet:
      "Concevez, sécurisez et automatisez l'infrastructure cloud haute disponibilité servant des milliers d'entreprises. Poste ouvert en télétravail complet en France et pays limitrophes francophones.",
    source: "Remotive",
    language: "fr",
  },
  {
    id: "fallback-fr-3",
    title: "Product Designer Senior / Design System Lead",
    company: "Alan",
    company_logo: "",
    url: "https://alan.com/careers",
    category: "Design & UX",
    categoryId: "design",
    categoryIcon: "🎨",
    tags: ["Figma", "Design System", "UI/UX", "User Research", "Prototyping"],
    job_type: "Full-time (CDI)",
    location: "Paris, France / Belgique (Full Remote)",
    region: "France & Francophonie",
    regionId: "france",
    regionFlag: "🇫🇷",
    salary: "60 000 € - 80 000 € / an",
    published_at: "2026-08-16T17:20:00.000Z",
    description_snippet:
      "Façonnez l'expérience santé de millions d'utilisateurs. Rôle 100% full remote avec culture de l'écrit, autonomie totale et rituels d'équipe conviviaux.",
    source: "Jobicy",
    language: "fr",
  },
  {
    id: "fallback-ww-1",
    title: "Staff AI Engineer / LLM Systems Architect",
    company: "Automattic",
    company_logo: "",
    url: "https://automattic.com/work-with-us/",
    category: "Data & IA",
    categoryId: "data_ai",
    categoryIcon: "🧠",
    tags: ["Python", "PyTorch", "LLM", "Vector DB", "FastAPI"],
    job_type: "Full-time",
    location: "Worldwide (Anywhere)",
    region: "Worldwide",
    regionId: "worldwide",
    regionFlag: "🌍",
    salary: "$140,000 - $190,000 / yr",
    published_at: "2026-08-17T07:15:00.000Z",
    description_snippet:
      "Architect and scale next-generation generative AI features for WordPress.com and Tumblr. 100% distributed workforce in over 90 countries since day one.",
    source: "Remotive",
    language: "en",
  },
  {
    id: "fallback-ww-2",
    title: "Senior Backend Engineer (Go / Distributed Systems)",
    company: "Doist (Todoist / Twist)",
    company_logo: "",
    url: "https://doist.com/careers",
    category: "Tech & Dev",
    categoryId: "tech",
    categoryIcon: "💻",
    tags: ["Golang", "PostgreSQL", "Redis", "Kafka", "gRPC"],
    job_type: "Full-time",
    location: "Worldwide (Remote)",
    region: "Worldwide",
    regionId: "worldwide",
    regionFlag: "🌍",
    salary: "$110,000 - $145,000 / yr",
    published_at: "2026-08-16T14:40:00.000Z",
    description_snippet:
      "Join an async-first company with 100+ team members in 35+ countries. Build reliable, low-latency sync systems for millions of daily active users.",
    source: "Jobicy",
    language: "en",
  },
  {
    id: "fallback-eu-1",
    title: "Senior Rust / WebAssembly Systems Developer",
    company: "1Password",
    company_logo: "",
    url: "https://1password.com/careers",
    category: "Tech & Dev",
    categoryId: "tech",
    categoryIcon: "💻",
    tags: ["Rust", "Wasm", "Cryptography", "Security", "Linux"],
    job_type: "Full-time",
    location: "Europe / UK (100% Remote)",
    region: "Europe",
    regionId: "europe",
    regionFlag: "🇪🇺",
    salary: "€85,000 - €115,000 / yr",
    published_at: "2026-08-17T06:45:00.000Z",
    description_snippet:
      "Help build and harden the cryptographic core and desktop apps of 1Password. Remote across European and UK timezones.",
    source: "Arbeitnow",
    language: "en",
  },
  {
    id: "fallback-eu-2",
    title: "Growth & Content Marketing Strategist (EMEA)",
    company: "Hotjar (Contentsquare)",
    company_logo: "",
    url: "https://www.hotjar.com/careers/",
    category: "Marketing & Sales",
    categoryId: "marketing_sales",
    categoryIcon: "📈",
    tags: ["Growth", "SEO", "Content", "B2B SaaS", "Analytics"],
    job_type: "Full-time",
    location: "Europe / Remote (EMEA)",
    region: "Europe",
    regionId: "europe",
    regionFlag: "🇪🇺",
    salary: "€60,000 - €80,000 / yr",
    published_at: "2026-08-16T11:00:00.000Z",
    description_snippet:
      "Lead international demand generation and organic acquisition campaigns across European markets. Fully remote with holiday co-working allowances.",
    source: "Arbeitnow",
    language: "en",
  },
  {
    id: "fallback-us-1",
    title: "Principal Cloud Security Engineer (GCP / Zero Trust)",
    company: "Stripe",
    company_logo: "",
    url: "https://stripe.com/jobs",
    category: "DevOps & Cloud",
    categoryId: "devops",
    categoryIcon: "☁️",
    tags: ["GCP", "Kubernetes", "IAM", "Zero Trust", "Terraform"],
    job_type: "Full-time",
    location: "US & Canada (Remote)",
    region: "Amériques",
    regionId: "americas",
    regionFlag: "🇺🇸",
    salary: "$185,000 - $240,000 / yr",
    published_at: "2026-08-16T18:00:00.000Z",
    description_snippet:
      "Scale and protect financial infrastructure processing billions of transactions. Work remotely from anywhere in North America.",
    source: "Remotive",
    language: "en",
  },
  {
    id: "fallback-us-2",
    title: "Senior Product Manager - Developer Platform",
    company: "Vercel",
    company_logo: "",
    url: "https://vercel.com/careers",
    category: "Product & Management",
    categoryId: "product",
    categoryIcon: "🚀",
    tags: ["Next.js", "Serverless", "Developer Experience", "Roadmap", "API"],
    job_type: "Full-time",
    location: "Americas / LATAM (Remote)",
    region: "Amériques",
    regionId: "americas",
    regionFlag: "🇺🇸",
    salary: "$160,000 - $210,000 / yr",
    published_at: "2026-08-15T20:10:00.000Z",
    description_snippet:
      "Drive the future of frontend cloud workflows and edge computing. Fully remote across North and South America.",
    source: "Jobicy",
    language: "en",
  },
  {
    id: "fallback-apac-1",
    title: "Senior Mobile Engineer (Flutter / React Native)",
    company: "Canva",
    company_logo: "",
    url: "https://lifeatcanva.com/",
    category: "Tech & Dev",
    categoryId: "tech",
    categoryIcon: "💻",
    tags: ["Flutter", "Dart", "iOS", "Android", "Mobile Architecture"],
    job_type: "Full-time",
    location: "APAC / Australia / Singapore (Remote)",
    region: "Asie & MEA",
    regionId: "apac_mea",
    regionFlag: "🌏",
    salary: "A$140,000 - A$180,000 / yr",
    published_at: "2026-08-16T04:20:00.000Z",
    description_snippet:
      "Empower the world to design on mobile devices. Fully remote across APAC timezones with generous home office stipend.",
    source: "Remotive",
    language: "en",
  },
];
